### ISSUE TITLE
County data

### ISSUE THREAD

**Issue by jnfoster** [CSStipendRankings/CSStipendRankings#35]
For the MIT Living Wage database, using county data in cases where city data doesn't exist seems slightly suspect. For example, Princeton's entry is currently based on Mercer County, which includes Trenton, and therefore drags the figure down significantly. (I don't think many Princeton PhDs live in Trenton.)

I don't have a proposed solution (and Princeton's leadership on stipends is super admirable), but for a PhD student trying to understand the actual cost of living, it very likely skews the results.

**Comment by mjc0608** [comment]
I actually agreed. We have noticed that the MIT living wage database seems not accurate and misestimates the living wage in a lot of places. We are looking for a solution as well. Any contribution is welcomed.

**Comment by jiong-zhu** [comment]
I would recommend that when there are both a county and a Metropolitan Area in the MIT Living Wage database that cover an institution, we compare the area size of the county and the Metropolitan Area on Google map, and go with the one that has the smaller area.

**Comment by UltimateJupiter** [comment]
Another potential source of data is the I-20 form the departments assign to international students. There is usually an official estimation of living cost as a student (though usually further skewed down in favor of the institutions). For Princeton in 2023-2024 it is 36600, which is even lower than the Mercer County data point.

**Comment by polochau** [comment]
All universities are required by law to provide "cost of attendance"(COA) estimates https://fsapartners.ed.gov/knowledge-center/fsa-handbook/2020-2021/vol3/ch2-cost-attendance-budget . COA is not a perfect (and neither is the Living Cost calculator's estimates) as different universities can compute their estimates differently. Also, special care needs to be taken to subtract the expenses have been already been covered by the universities, so that we do not double count an expense (e.g., [health insurance expense being double counted for GT](https://github.com/CSStipendRankings/CSStipendRankings/pull/31#issuecomment-1537151687)) 
However, future students will at least become aware of the official COA figures provided by the universities they are considering, and the possible large differences between the figure computed by the living cost calculator and the official COA. Examples where the COA and the calculator showing vast differences:
- UC Santa Cruz https://financialaid.ucsc.edu/cost-to-attend/graduate-costs.html
- University of Maryland, College Park https://billpay.umd.edu/GraduateTuition

**Comment by TonyZhangND** [comment]
@polochau I opened issue #48 to add support for university COA

**Comment by ahoho** [comment]
@polochau yea, I don’t think it’s a coincidence both those schools are in high CoL areas (I’m at UMD). The universities are incentivized to misrepresent costs, and I think the federal regulations are sufficiently lax to allow for flexibility in the estimates

**Comment by mjc0608** [comment]
This issue is about a limitation which is now discussed in Q&A. I'm closing this issue.
