### ISSUE TITLE
9 month stipends

### ISSUE THREAD

**Issue by CeeZh** [CSStipendRankings/CSStipendRankings#41]
Thanks for the awesome work! Really love it. 

Is it possible to separate 12 month stipends and 9 month stipends? Since many CS graduate students do internships in the summer, 9 month stipends might make more sense.

**Comment by noah-curran** [comment]
What is being asked here? Do you want a separate column or a toggle? Also, how do you propose dealing with institutions that use 8-month stipends for the non-summer period?

As an aside, I personally do not see internships as a relevant aspect of this list. It should not be necessary to consider internships in order to sustain the financial feasibility of CS PhD programs, especially since international students are limited in the number of internships they can go on. I think your idea is a good one for showing the guaranteed vs. extrapolated 12-month funding comparison (as mentioned in https://github.com/CSStipendRankings/CSStipendRankings/issues/17#issuecomment-1536631538).

**Comment by ahoho** [comment]
I think a toggle is most useful, something like
- Guaranteed (the default ranking, basically what's in the offer letter)
- Monthly, based on the academic year pay (this normalizes the 8-vs-9-month issues)
- 12-month with a 20-hour / week summer appointment
- 12-month @ 40-hour

**Comment by noah-curran** [comment]
> * 12-month @ 40-hour

@ahoho Out of curiosity, are there some programs that pay at a 40 hr/wk rate as a guarantee? I've heard of some fringe cases when someone is teaching full-time, but not for research. Or is this data more of a "suppose if they implemented this policy of pay"?

**Comment by ahoho** [comment]
Ah, sorry, that's a typo, it should have said "12-month @ 40-hour summer", which I think is effectively what's guaranteed by, e.g., Stanford, Princeton, etc.

**Comment by noah-curran** [comment]
Gotcha! I have heard of that. I think from what I have read on the bottom of [csstipendrankings.org](https://csstipendrankings.org/) they are going to consider adding that in the near-future.

**Comment by animesh-garg** [comment]
I think a lot of salary differential is because of the summer @40-week or @20-week pay differential. 
At many schools, this is often the choice of PI or dept. 

Hence a monthly academic year payments are best normalization. 
Summer should be treated separately.

**Comment by animesh-garg** [comment]
We have an extended discussion on 9-month vs 12 month going on here as well. #17

**Comment by mjc0608** [comment]
Hello guys, thanks for the discussion! We have updated the stipend reporting google form to include the amount of summer funding, and whether summer funding is guaranteed. If you have this information for your department, please submit!

**Comment by mjc0608** [comment]
We now have a function to show "guaranteed funding". I'm closing this issue.
