### ISSUE TITLE
Include University official estimated living cost as an alternative data source.

### ISSUE THREAD

**Issue by TonyZhangND** [CSStipendRankings/CSStipendRankings#48]
This enhancement adds support for alternative sources for estimated cost of living. 
In particular, we want to add support for universities' official estimated costs, which is published on their website or written in the I-20 forms, as proposed in #35 and #43.
There should be a toggle to select between this new source and the MIT Calculator source, as mentioned.

**Comment by ahoho** [comment]
I mentioned it [in this comment](https://github.com/CSStipendRankings/CSStipendRankings/issues/17#issuecomment-1537229668), but I believe it is unwise to use university estimates.

Unlike the MIT numbers, they are not transparent. At my institution, they are several thousand dollars below the actual cost of living (we are located in one of the most expensive metro areas in the country, but the university estimates room and board to be the same as IU in Bloomington or UW in Madison, both dramatically cheaper cities).

It’s my understanding universities estimate these figures in part through surveys. This has a clear methodological problem: if you only pay your workers a low amount, then they are forced to spend below that amount, irrespective of actual costs.

I guess I’m reluctant to give any air to biased estimates

**Comment by TonyZhangND** [comment]
I see. I agree with you that universities are highly incentivized to underestimate these costs, and I can see that happening here at Michigan --- no way they will publish a cost higher than their stipend. But @polochau's argument for transparency also has merit. 
Any opinions @mjc0608 @jiong-zhu @shibo-chen ?

**Comment by mjc0608** [comment]
I actually think @ahoho's point makes sense. For ranking purposes we need numbers calculated either 1) by the same institution, or 2) using the same method. The lack of transparency in university-provided cost estimation is indeed a concern.

**Comment by mjc0608** [comment]
Instead, can we propose a metric based on the price of 2b2b apartments and the price of McNuggets? I guess there are two universally-available things.

**Comment by TonyZhangND** [comment]
We can check the price by ordering McNuggets on the Macdonald's app from across the country 🐓

**Comment by TonyZhangND** [comment]
On a serious note, I think the cost of rent relative to income is a very good metric. The challenge is with getting good rent information for reasonable housing, e.g. exclude both slums and luxury apartments

**Comment by ahoho** [comment]
[Another method I’ve seen is to use relative CoL and index the stipends to a common reference point](https://profession.mla.org/english-phd-stipends-in-the-united-states-statistical-report/). So everything is put in terms of “Boston-dollars”, or something. The link has one reference for this, but there are others as well.

It doesn’t factor in things like subsidized housing or differences in healthcare, but maybe we could account for that

**Comment by ahoho** [comment]
> On a serious note, I think the cost of rent relative to income is a very good metric. The challenge is with getting good rent information for reasonable housing, e.g. exclude both slums and luxury apartments

[HUD Fair Market Rents are a good resource](https://www.huduser.gov/portal/datasets/fmr.html). I think they underpin the MIT numbers

**Comment by noah-curran** [comment]
> But @polochau's argument for transparency also has merit.

Why is using a biased party's metric considered a good data point? And what does it have to do with being transparent? Should we also include a column of biased data points from various grad union organizations? (Without naming names, we know these also exist.) My thought is that the point of sticking to something like MIT CoL calculator to use something from a third, uninvolved party.

**Comment by TonyZhangND** [comment]
Yeah. I guess I don't know how biased university figures are. I suspected them to be biased, but didn't know for sure how much merit they have. 

> [HUD Fair Market Rents are a good resource](https://www.huduser.gov/portal/datasets/fmr.html). I think they underpin the MIT numbers 
This one is good, although it will underestimate cost for very expensive districts, e.g. Manhattan vs Metro NY.

**Comment by shibo-chen** [comment]
I think it's going to be very hard for us to come up with an accurate cost of living estimation. Student apartments and school districts are also very specialized markets that don't necessarily follow any number we can easily find.  

Another way is to omit the absolute value of the cost of living. Standardize the cost by comparing it to a set baseline(i.e., Ann Arbor) using conversion tool: https://www.salary.com/research/cost-of-living

I think we should be clear about whether our primary goal is to compare universities or present an accurate image of the financial status of grad students. If it's the former, then we don't need to care too much about whether the absolute CoL is accurate. If we care about the later, then we will have more work to do.

**Comment by noah-curran** [comment]
> I guess I don't know how biased university figures are.

Right, same. It's impossible to know without the transparency, which makes it all the more worrisome. I feel uncomfy including data points that we do not understand. At least since MIT CoL calculator is transparent, we've been able to have healthy debates about where issues occur. Such debates are impossible with the university-provided data points.

**Comment by TonyZhangND** [comment]
> I think we should be clear about whether our primary goal is to compare universities or present an accurate image of the financial status of grad students. 

I personally began with the idea of the former, but many users are demanding the latter. Like I personally wouldn't take the MIT calculator as some ground truth, and the disclaimer on the site emphasizes this. But there are lots of complaints about that being somewhat misleading

**Comment by shibo-chen** [comment]
If so, I suggest we can switch to ratio based ranking? I understand where some people come from that if we suggest one absolutely cannot self sustain financially during grad school then people might be discouraged from considering it as their career option.

**Comment by noah-curran** [comment]
> But there are lots of complaints about that being somewhat misleading

No metric is perfect, and as scientists we all understand this. The complaints about MIT CoL calculator give reviewer 2 energy. We can continue to optimize it to be more precise (and make a few people happy that their institution doesn't look as bad compared to the others), but I am doubtful that the larger painted picture is going to change much.

**Comment by polochau** [comment]
Cost of attendance is required by federal law — it’s not perfect, or in your words “biased”. COA needs to at least include some common categories like housing and food, and future students will at least be informed by what each university is using for those categories. Some universities’ food estimates are the same as dining plan costs that are exact and we can tell exactly what are included, thus can be transparent. How the calculator’s estimates are used currently is that they aren’t broken down so we don’t know what are really included and what are the amount for each component (again, it seems we could tell what are exactly included via the calculator’s data request).

I hope everyone would understand the possible repercussions of not striving to be accurate, even if that is hard. Creating a potentially high-impact ranking automatically comes with a lot of responsibilities, which I hope was well understood. By now, I’m sure we have all recognized that the Living Cost estimates of some of the schools are highly unrealistic (e.g., -1500 per month). It sounds like some comments here are suggesting that it is OK for some schools to appear way worse than they actually are (and who knows, perhaps they could actually in the positive, instead of -1.5k, if only the estimate is closer to reality!), because it is better to use a convenient data source that fits an intended narrative. If that indeed is the mindset, I’m glad that it has been brought to light —- but I am disappointed to learn that that is the case. 

Thank you for everyone’s contributions, and have a great evening.

**Comment by jiong-zhu** [comment]
I would support adding alternative sources for estimated cost of living (including the universities' official estimated costs), and have a toggle to select among different data sources. While no data source is perfect or biased fee, and people have different opinions on different data sources, I would entrust the users to make their own decision. We could also have separate CSV files for stipend and cost of living, so that other data sources and ways of estimating cost of living could be more easily contributed and documented by the community.

**Comment by TonyZhangND** [comment]
Agree with @jiong-zhu

**Comment by noah-curran** [comment]
> It sounds like some comments here are suggesting that it is OK for some schools to appear way worse than they actually are

No one is suggesting this. The conversation here is about finding unbiased metrics that accurately reflect the typical CoL.

**Comment by polochau** [comment]
> > It sounds like some comments here are suggesting that it is OK for some schools to appear way worse than they actually are
> 
> No one is suggesting this. The conversation here is about finding unbiased metrics that accurately reflect the typical CoL.

Thanks for the comment. It helps that all the comments here are public, so everyone can read them and make judgements.

**Comment by mjc0608** [comment]
Should we add some comments on the website explaining why we do not use the living cost estimation from the university?

**Comment by ahoho** [comment]
@polochau I do want to push back a bit—just because the CoA is required by law doesn’t mean it’s accurate. I’ve spoken to our director of financial aid and submitted FOIA requests and it’s still less clear to me than the MIT number. University administrators also have a narrative to push.

That said, I am confident saying it is biased low. Because it relies in part in expenditure surveys, graduates are necessarily constrained by what they are paid. For example, at UMD, many share the same room.

I think having other third party CoL numbers as an option makes sense—I’m on mobile, but the MLA put out an English PhD ranking with another metric, ranking everything relative to CoL in a common index (I think Boston).

**Comment by shibo-chen** [comment]
Just an overarching and personal comment:

If we look at the stipends schools offer across the board, it is obvious that no school can really point to themselves and say they have paid their fair share, even for schools ranked highly on the list, i.e. Princeton. Everyone in grad school is already taking a significant pay cut for what they are worth. I don't want to get into an industry vs. academia discussion. Let me just end this paragraph acknowledging that students are also voluntarily taking this hit because we know there is more to life and more factors to consider other than $$.

There are anecdotes online arguing how students are able to live with significantly lower numbers than the MIT number. Good for them! But I know it's not for me. I want to be able to support my hobbies and eat out sometimes.  I want to keep my Netflix and Spotify subscriptions. I also need to find a barber and have a haircut every month. I don't think these are unreasonable asks and I don't think students should endure whatever the school has offered to them and lower their living standard just to be able self-sustain financially.

**My only concern is that some younger students will look at these numbers and think to themselves that grad school does not worth it.** But for the sake of the data itself, I don't believe there is any bias in our data or that MIT CoL is an exaggeration. If some schools look bad on the ranking, good, that's the point. Pay students more and improve their benefits, then they get to climb on the ranking. It's a win-win for everyone.

**Comment by lmwnshn** [comment]
> ... The conversation here is about finding unbiased metrics that accurately reflect the typical CoL.

As an alternative to estimating the CoL (which may vary wildly depending on your personal needs and wants), what are your thoughts on indexing against retail wages? This would be an option for reporting and sorting by `(annual phd stipend - annual mean wage of cashiers in the area)`. Personally, this mirrors how I think about savings: everyone needs to live, so if they can live on `X`, then you should be able to save `stipend - X`.

As a data source, the BLS: https://data.bls.gov/oes/#/home (One occupation for multiple geographic areas > (ctrl-f) Cashiers > Metropolitan or Non Metropolitan Area > All MSA in this list > All Data Types > HTML output > submit).

**Comment by noah-curran** [comment]
> > ... The conversation here is about finding unbiased metrics that accurately reflect the typical CoL.
> 
> 
> 
> As an alternative to estimating the CoL (which may vary wildly depending on your personal needs and wants), what are your thoughts on indexing against retail wages? This would be an option for reporting and sorting by `(annual phd stipend - annual mean wage of cashiers in the area)`. Personally, this mirrors how I think about savings: everyone needs to live, so if they can live on `X`, then you should be able to save `stipend - X`.
> 
> 
> 
> As a data source, the BLS: https://data.bls.gov/oes/#/home (One occupation for multiple geographic areas > (ctrl-f) Cashiers > Metropolitan or Non Metropolitan Area > All MSA in this list > All Data Types > HTML output > submit).

Seems like an interesting idea. Your hidden assumption seems to be that cashiers in the area should be able to live on their wages. Is this necessarily true? I generally think I agree from observation that cashiers are usually just able to get by, but I also don't have real data to prove that.

There is also the possibility that cashiers commute from a town over (where it's cheaper) in order to survive on the income. If we use cashiers as a basis of comparison and this lifestyle is required of them, then we are subtly endorsing that PhD workers should be subject to the same lifestyle of commuting towns over. (Injecting my personal opinion as an aside, given the hours and effort required of PhD workers, I'm hesitant to agree that it's even feasible to live further away.)

Just some food for thought. I like the idea and reasoning, but it seems from prior discussion in this thread that people make stories from data, so we cannot leave these stones unturned. Would be interested to hear your thoughts.

**Comment by TonyZhangND** [comment]
Yeah @noah-curran @lmwnshn . Minimum wage service workers definitely can't afford to live in Ann Arbor, https://www.michigandaily.com/news/ann-arbor/local-businesses-struggle-fill-positions-lose-workforce-ann-arbor-rent-rates/.

@ahoho @polochau I am _for_ collecting official university estimates, just to see what they look like. Perhaps users can determine for themselves their merit. A couple of data points:
- UMich says food and housing is $17,780 for 9 months; I pay $14,400 over 9 months for rent and utilities.
- Columbia says that food and housing should cost $25,560 for 9 months. That's $2800 a month to live in Manhattan, and their disclaimer is even more outrageous: see image.

![Screenshot 2023-05-07 at 11 10 44 AM](https://user-images.githubusercontent.com/15366567/236685954-31409d7c-80d1-4ebb-b4c1-0fc2b6650a56.png)

**Comment by ahoho** [comment]
I think Columbia has subsidized housing. And I know that UMich has the
largest CoA overestimate relative to MIT living wage in the Big Ten.

I’m reluctant to include the official numbers because prospective students
may not know how to interpret them. Ours are so out of sync with reality I
hate to give them air, but I suppose if we include a disclaimer that is
fair.

Regarding cashier wages, etc: I don’t think we should be reinventing the
wheel here. This is an established problem and the MIT number is
well-motivated and the methodology is clear (as are other CoL numbers like
that from the English PhD rankings I linked).

**Comment by mjc0608** [comment]
Close due to inactivity.
